"""user table

Revision ID: 68ed24ba13fe
Revises: 
Create Date: 2025-03-22 20:54:43.235240

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '68ed24ba13fe'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('election',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('start_time', sa.DateTime(), nullable=True),
    sa.Column('end_time', sa.DateTime(), nullable=True),
    sa.Column('election_status', sa.String(length=20), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('email', sa.String(length=120), nullable=True),
    sa.Column('password_hash', sa.String(length=128), nullable=False),
    sa.Column('campus', sa.String(length=15), nullable=False),
    sa.Column('role', sa.String(length=20), nullable=False),
    sa.Column('registered', sa.Boolean(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.create_index(batch_op.f('ix_user_email'), ['email'], unique=True)

    op.create_table('ballot',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('candidate_list', sa.String(), nullable=False),
    sa.Column('campus', sa.String(length=20), nullable=False),
    sa.Column('selections', sa.Integer(), nullable=False),
    sa.Column('election_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['election_id'], ['election.id'], name='fk_ballot_election'),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('candidate',
    sa.Column('candidate_id', sa.Integer(), nullable=False),
    sa.Column('candidate_name', sa.String(length=45), nullable=False),
    sa.Column('manifesto', sa.String(length=1000), nullable=False),
    sa.Column('campus', sa.String(length=45), nullable=False),
    sa.Column('number_votes', sa.Integer(), nullable=False),
    sa.Column('status', sa.Boolean(), nullable=False),
    sa.Column('ballot_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballot.id'], name='fk_candidate_ballot'),
    sa.PrimaryKeyConstraint('candidate_id')
    )
    op.create_table('vote',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('time_stamp', sa.DateTime(), nullable=True),
    sa.Column('ballot_id', sa.Integer(), nullable=False),
    sa.Column('user_id', sa.Integer(), nullable=False),
    sa.ForeignKeyConstraint(['ballot_id'], ['ballot.id'], name='fk_vote_ballot'),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], name='fk_vote_user'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('vote')
    op.drop_table('candidate')
    op.drop_table('ballot')
    with op.batch_alter_table('user', schema=None) as batch_op:
        batch_op.drop_index(batch_op.f('ix_user_email'))

    op.drop_table('user')
    op.drop_table('election')
    # ### end Alembic commands ###
