"""empty message

Revision ID: ced1761a6a05
Revises: 68ed24ba13fe
Create Date: 2025-03-23 12:25:54.328826

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'ced1761a6a05'
down_revision = '68ed24ba13fe'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('votes', sa.Integer(), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot', schema=None) as batch_op:
        batch_op.drop_column('votes')

    # ### end Alembic commands ###
