"""election table

Revision ID: da0279ea2c60
Revises: fa23af9fee4b
Create Date: 2025-03-24 04:10:58.562736

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'da0279ea2c60'
down_revision = 'fa23af9fee4b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.add_column(sa.Column('election_name', sa.String(length=45), nullable=False))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('election', schema=None) as batch_op:
        batch_op.drop_column('election_name')

    # ### end Alembic commands ###
