"""ballot table

Revision ID: eb1412f387c4
Revises: da0279ea2c60
Create Date: 2025-03-24 10:38:48.363204

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'eb1412f387c4'
down_revision = 'da0279ea2c60'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('status', sa.Boolean(), nullable=False))
        batch_op.drop_column('candidate_list')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('ballot', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_list', sa.VARCHAR(), nullable=False))
        batch_op.drop_column('status')

    # ### end Alembic commands ###
