"""empty message

Revision ID: fa23af9fee4b
Revises: 79ae7c02ef3b
Create Date: 2025-03-23 21:13:30.692550

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'fa23af9fee4b'
down_revision = '79ae7c02ef3b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('id', sa.Integer(), nullable=False))
        batch_op.add_column(sa.Column('fullname', sa.String(length=45), nullable=False))
        batch_op.drop_column('candidate_id')
        batch_op.drop_column('candidate_name')

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('candidate', schema=None) as batch_op:
        batch_op.add_column(sa.Column('candidate_name', sa.VARCHAR(length=45), nullable=False))
        batch_op.add_column(sa.Column('candidate_id', sa.INTEGER(), nullable=False))
        batch_op.drop_column('fullname')
        batch_op.drop_column('id')

    # ### end Alembic commands ###
